#### CI CONFIG

language:   java

<language version>: #depending on language
  - oraclejdk8
  - openjdk8

#### special tags for ruby language ####
gemfile:
bundler_args: arg 1
#### end special tags for ruby language ####

branches:
  only:
    - master
    - release/*
    - basicImplementatinTODO
  except:
    - feat*

git:
   submodules: false

services:

env:
  - ENV1:
    ENV2:
  - ENV1:
    ENV2:
global:
  - ENVG1:
  - ENVG2:

matrix:
  include:
    - ENV1:
  exclude:
    - ENVG2:
  allow_failures:

build:
  pre_ci:
  pre_ci_boot:
  ci:
  post_ci:
  on_success:
  on_failure:
  cache:
  cache_dir_list:
  advancedReporting:
  push:

integrations:
  notifications:
    - integrationName:
      type:
      recipients:
      branches:
        only:
          - master
      on_success: always | change | never
      on_failure: always | change | never
      on_cancel: always | change | never
      on_start: always | never
      on_pull_request: always | never
       #### special tags for email type ####
      sendConsoleLogs: true
      sendCoverageReports: true
      #### special tags for email type ####

  key:
    - integrationName: my_custom_key
      type: sshKey

  deploy:                                   # deprecated
    - integrationName: "aws-eb-integration"
      type: aws
      target: eb_paas
      platform:
      application_name:
      env_name:
      region:
      #### special tags for docker app ####
      image_name:
      image_tag:
      bucket_name:
      #### special tags for docker app ####

#### END CI CONFIG

#### RESOURCES CONFIG (GLOBAL ACROSS SUBSCRIPTION)

resources:
  - name:
    type:
    integration:
    pointer:
    seed:
    version:

#### END RESOURCES CONFIG

#### JOBS CONFIG (GLOBAL ACROSS SUBSCRIPTION)

jobs:
  - name: 
    type:          
    on_start:
      - NOTIFY:    
    steps:
      - IN:       
        switch:     off
      - IN:        
      - IN:         
        versionName: 
      - IN:         
        versionNumber: 
      - IN:         
        applyTo:

      - IN:         
        applyTo:
          - manifest:
            image:    
            port:     
      - IN:         
        showBuildStatus: true
      - IN:         
        force:      true
      - TASK:
        - script:   
        - script:   
      - OUT:      
      - OUT:       
        replicate: 
    on_success:
      - script:     echo "SUCCESS"
    on_failure:
      - script:     echo "FAILED"
      - NOTIFY:     
    on_cancel:
      - script:     echo "CANCEL"
    always:
      - script:     pwd

#### END JOBS CONFIG
